name: puu1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  get: ^4.6.6
  http: ^1.2.2
  shared_preferences: ^2.3.3
  sp_util: ^2.0.3
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  get_storage: ^2.1.1
  flutter_svg: ^1.1.6
  geolocator: ^13.0.2
  google_fonts: ^6.2.1
  table_calendar: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/images/
    - asset/icon/
